### ISSUE TITLE
Suggestion: Lambda Simplification for creation of 'is_protected' column

### ISSUE THREAD

**Issue by Caealana** [grolimur/intro-data-capstone-biodiversity#1]
https://github.com/grolimur/intro-data-capstone-biodiversity/blob/a0311a4a58cc3778ca13b702c9f9ec8ff773e7fd/biodiversity/biodiversity.py#L166-L171
Your lambda for creating the 'is_protected' column works correctly! However, you can simplify this code so that you don't need to use an if/else structure to determine the correct value. Since we just need to check if the conservation status is 'No Intervention", we can use the != operator against that string to get back a boolean that corresponds to the answer to that check.

`species['is_protected'] = species.conservation_status != 'No Intervention'`

This code takes the whole species.conservation_status column as a list/series of string values. It compares each string entry to 'No Intervention'. From each of these comparisons, a boolean True or False value is returned to generate a series of True and False values that matches the length of our data frame.

**Comment by grolimur** [comment]
Same comment as for #3 .
