### ISSUE TITLE
Great job: Contingency Tables

### ISSUE THREAD

**Issue by Caealana** [grolimur/intro-data-capstone-biodiversity#2]
https://github.com/grolimur/intro-data-capstone-biodiversity/blob/a0311a4a58cc3778ca13b702c9f9ec8ff773e7fd/biodiversity/biodiversity.py#L294

Nice job - All of your contingency tables are correct. This demonstrates your mastery of the statistical concepts taught in this course.

**Comment by grolimur** [comment]
Thanks!
