### ISSUE TITLE
Note: Lambda simplification for creation of is_sheep column

### ISSUE THREAD

**Issue by Caealana** [grolimur/intro-data-capstone-biodiversity#3]
https://github.com/grolimur/intro-data-capstone-biodiversity/blob/a0311a4a58cc3778ca13b702c9f9ec8ff773e7fd/biodiversity/biodiversity.py#L341

Your lambda here works great to filter which rows are sheep species. There is another method to create the is_sheep column without using an if/else structure:
```
species['is_sheep'] = species.common_names.apply(lambda x: 'Sheep' in x)
```
This works because we only need as a result a boolean answer to if the word 'Sheep' is in the common name of the animal. This code will take the whole column of common names. A lambda is applied to each entry of this column and searches to see if the word 'Sheep' is in each entry. The lambda returns True if 'Sheep' is in the string, and it returns False otherwise. The number of boolean values returned matches the number of rows in the dataframe.

**Comment by grolimur** [comment]
I'm still a little stuck with shortening the code. I hope practice will help with that.
