### ISSUE TITLE
Note: No need for a comparison operator for is_sheep column

### ISSUE THREAD

**Issue by Caealana** [grolimur/intro-data-capstone-biodiversity#4]
https://github.com/grolimur/intro-data-capstone-biodiversity/blob/a0311a4a58cc3778ca13b702c9f9ec8ff773e7fd/biodiversity/biodiversity.py#L355-L363

You don't need to compare is_sheep to True since is_sheep is already a column of True and False values representing whether or not the row is a sheep. So if is_sheep is True and we do is_sheep == True, we get True back. If is_sheep is False and we do is_sheep == True, we get back False. So using the comparison operator just gives us back our original boolean values from the column.

**Comment by grolimur** [comment]
Oh! I got it! You are right.
