### ISSUE TITLE
Summary: Meets Expectations

### ISSUE THREAD

**Issue by Caealana** [grolimur/intro-data-capstone-biodiversity#5]
Overall, this was a great project! 

I won't have too much to say about your code, as all of your code was functionally correct. There were only some minor areas where your code could have been made more efficient. However, efficiency tricks will become more second nature as you code more. You followed many of the best conventions concerning indentation and variable naming conventions. This helped in making your python code easily readable. [Here](https://www.python.org/dev/peps/pep-0008/) is more information on python styling conventions if you are interested.

 I would suggest you practice adding in your own comments and a README to this github repository to give some context to your code. Comments answer questions like 'What were you thinking when you writing this code?' and 'What is the purpose of this chunk of code? Are there currently any issues with it?" [Here ](https://guides.github.com/features/wikis/) is a helpful guide for creating READMEs that give a good introduction to your project.

On your presentation:
I would suggest you introduce your project before you jump into your data and calculations. You should answer questions like, "What problem are you trying to solve?", "Why is this problem important?", "What information do you need to know about the problem?". This will help your audience feel more involved and engaged with your work.

You did well in not letting your slides become too cluttered or overfilled. I like how you approached dividing up the dataset information so that each slide had a clear topic. 

I would suggest you present your two chi-square tests separately. For each of your tests, you should present the null hypothesis, the p-value, and the interpretation of the p-value. Here is an example of that format: 
<img width="497" alt="screenshot at mar 19 21-05-59" src="https://user-images.githubusercontent.com/14001120/37628701-575e3906-2bb9-11e8-85e4-040888cc74ed.png">
Providing these details about your tests ensures that you have enough evidence to support your recommendations.

**Comment by grolimur** [comment]
@Caealana Thanks a lot for the feedback and the useful tips!
